name: rcspy
description: "An app to check if a apps firebase remote config is publicly accessible"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  device_packages:
    git:
      url: https://github.com/tusharonly/device-packages.git
      path: device_packages
  archive: ^4.0.3
  path_provider: ^2.1.5
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  comments_remover: ^1.0.2

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf